### ISSUE TITLE
Relative test naming / syntax is confusing

### ISSUE THREAD

**Issue by DevilXD** [pytest-dev/pytest-order#24]
Hello o/

So, I've wanted to give this library a shot. I'm in the middle of moving from `pytest-dependency`, and I really can't get my tests to work with it. All I want, is to specify that certain tests are allowed to run only after others specified, which is why I'm pretty much exclusively using `@pytest.mark.order(after=...)` everywhere.

Here's the code: https://github.com/DevilXD/aRez/compare/dev...order

And the error I'm getting:
```
WARNING: cannot execute test relative to others: test_misc.test_enum test_misc.test_cache tests.test_endpoint.test_session test_player.test_player_history test_api.test_get_match test_player.test_player_history test_player.test_player_status test_server_status_merge test_endpoint.test_session test_endpoint.test_session test_enum test_endpoint.test_session test_cache test_api.test_bounty test_api.test_get_match test_match.test_live_match test_player.test_player_history test_player.test_player_loadouts test_player.test_player_champion_stats test_cache test_player.test_player_history
tests.test_player.test_player_expand - ignoring the marker.
```
Python 3.8.8, pytest 6.2.3 and latest this lib (0.10.0) versions.

Here are the test names I've tried, for `tests/test_misc.py::test_enum` as an example:
```py
test_enum
test_misc.test_enum
tests.test_misc.test_enum
```
Again, none of them appear to make the warning go away, even when I rigorously change them everywhere, making sure to not miss anything.

Regardless, this leads me to the main topic, which I wanted to ask about here. Why are the tests referred to like this? Why is `tests/test_misc.py::test_enum` turned into `tests.test_misc.test_enum` or `test_misc.test_enum` (or idk, I never got it to work), especially since the library itself appears to have to convert it back to the previous form here: https://github.com/pytest-dev/pytest-order/blob/70b3f55aa46b79034a16acfaabca9d9eee1d8482/pytest_order/sorter.py#L201

Additionally, why a space as a separator? It's quite hard to notice exactly where each dependency starts and ends here:
`pytest.mark.order(after="test_misc.test_enum test_misc.test_cache")`
..., not even talking about something like this:
```py
@pytest.mark.order(after="test_cache test_api.test_bounty test_api.test_get_match test_match.test_live_match test_player.test_player_history test_player.test_player_loadouts test_player.test_player_champion_stats")
```
Fortunately, this one can be broken down a little, utilizing Python's ability to concat strings at compile time:
```py
@pytest.mark.order(after=(
    "test_cache "  #  notice a space after each element
    "test_api.test_bounty "
    "test_api.test_get_match "
    "test_match.test_live_match "
    "test_player.test_player_history "
    "test_player.test_player_loadouts "
    "test_player.test_player_champion_stats"
))
```
But still. Wouldn't it be better and easier for the user, to refer to tests by their ID labels? They're displayed when you run `pytest` with the `-v` flag, making it easy to just copy'n'paste where you'd want an order dependency to exist. Also, wouldn't a list of strings work better than a "space separated" single string? This is how it would/could look like:

```py
@pytest.mark.order(after=["tests/test_misc.py::test_enum", "tests/test_misc.py::test_cache"])
def test_thing():
    ...
# can be easily broken down if the line would get long too, not everyone knows that you can concat strings at compile time
@pytest.mark.order(after=[
    "tests/test_misc.py::test_enum",
    "tests/test_misc.py::test_cache",
])
def test_thing():
    ...
```

I know a change like this would be breaking a little, but it'd be easy to adapt it. Doing some quick searching, it appears that no one tried to use the `before` and `after` kwargs from this library yet, as the relevant results point at this repo only. This doesn't take into account private repos, or things not hosted on github, but still. Note - these are github-wide searches.

https://github.com/search?q=pytest.mark.order%28before&type=code
https://github.com/search?q=pytest.mark.order%28after&type=code

Please consider changing this as shown.

**Comment by mrbean-bremen** [comment]
Thanks for the extensive input and the suggestions. 

First, the currently released version (0.10.0) does not support more than one relative marker - I have added this only [recently](https://github.com/pytest-dev/pytest-order/blob/main/CHANGELOG.md). You have probably checked the [dev branch documentation](https://pytest-dev.github.io/pytest-order/dev/) instead of the [release documentation](https://pytest-dev.github.io/pytest-order/stable/). Can you please check if you have the same problem with the main branch? 

About your suggestions:
Changing the syntax for several markers: I was unsure about that myself. The main reason I did it this way was to make the default case (only one marker) most convenient, so I didn't want to add the list notation as mandatory (this is a common pitful in `pytest-dependency`). I still think that the main usage will be a single dependency, so I don't want to change that, but I could change the syntax for several markers to the list syntax as in `pytest-dependency`, which was what I actually considered first. I can make this change without problems, as the version is not released yet.

The notation of the markers: I found this syntax more readable at the time, but I agree that the nodeid may be a better (more standard) way to use. I have considered this while I was adding support for `pytest-dependency`, I just wasn't sure about it, also because it is a breaking change. But you are probably right that this is not used yet, so it should hopefully not have a big impact on existing code. I would like to retain the current behavior with regard to scopes though, e.g. you have to define only as much as needed of the nodeid for the current scope, without the need to explicitly defining a scope.

Nevertheless, as a breaking change this would demand a new major version (1.0) - I try to follow semantic versioning here. I also plan to drop Python 2.7 and 3.5 support for that version. 

But before doing any changes I would first like to understand why it does not work for you, and fix any bugs.

**Comment by DevilXD** [comment]
> First, the currently released version (0.10.0) does not support more than one relative marker - I have added this only recently.
> Can you please check if you have the same problem with the main branch?
> But before doing any changes I would first like to understand why it does not work for you, and fix any bugs.

I've reinstalled the library from the github repo, and used the same naming I went with the first time I tried - and everything worked! Looks like that was the problem 😅

>You have probably checked the dev branch documentation instead of the release documentation.

Honestly, I'm not sure how did that even happen. I swear I was looking at the release documentation, but then somehow ended up switching to dev documentation mid-way, I guess. That's my bad, apologies.

> make the default case (only one marker) most convenient, so I didn't want to add the list notation as mandatory
> I can make this change without problems, as the version is not released yet.

First of all, thank you for considering =) That'd be pretty cool. It should be as easy as:

```py
after_value: Union[str, List[str]]  # the contents of the 'after' kwarg and the thing you'll be iterating over later

if not isinstance(after_value, list):
    # make it iterable by wrapping it in a single-item tuple (faster than a single-item list, but your choice)
    after_value= (after_value,)
    # after_value= [after_value]

# iterate over it
for thing in after_value:
    ...
```

> I would like to retain the current behavior with regard to scopes though, e.g. you have to define only as much as needed of the nodeid for the current scope, without the need to explicitly defining a scope.

I'm perfectly fine with that, as long as it's going to make sense. In my case, I'll probably be using only session and local/module scopes anyway. The nicest thing about node IDs, is that one can just copy them directly from pytest (and optionally trim them, to change the scope), while the current syntax required me to do a bunch of replacing slashes, double colons and `.py` with dots, and it never ended up working in the end anyway (but now I know why 😅), so I think that'll be a much better solution in the long run 👍

**Comment by mrbean-bremen** [comment]
As you may have noticed, I have meanwhile changed the behavior for multiple markers in main as you have suggested. I will probably make a new minor release with that addition (I wanted to first fix any bug you found - but that is not needed, as it seems now 😄), and handle the change to nodeid later.

**Comment by DevilXD** [comment]
Sounds good! For the record, I'd still recommend using tuples for wrapping iterables, as they're about 5x faster to construct than a list: https://i.imgur.com/dX5iMFk.png

It's not that necessary (both work), but it's a simple speed optimization, and a small tip for the future 😊

**Comment by mrbean-bremen** [comment]
Yeah, I missed that - already did this locally now, thanks. It doesn't really matter performance-wise in this case (most time is spent elsewhere), but it's a good practice, anyway.
